name: test_random_with_column_flutter_apl
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter_bloc: ^8.1.5
  get:
  flutter:
    sdk: flutter
  provider: ^6.1.2  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter icons:  
  android: true
  ios: true
  image_path: 'lib/assets/AppIcon.png'  

flutter:
  uses-material-design: true
